name: hotel_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

# for ui
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1

# for data | state
  dio: ^5.3.2

  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  riverpod_annotation: ^2.1.0

  flutter_riverpod: ^2.3.5
  hooks_riverpod: ^2.3.5
  flutter_hooks: ^0.18.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
  # for data | state
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  freezed: ^2.3.2
  riverpod_generator: ^2.2.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

