name: hotel_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

# for ui
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  mask_text_input_formatter: ^2.5.0
  spider: ^4.2.2
  flutter_svg: ^2.0.7

# for data | state
  dio: ^5.3.2

  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  riverpod_annotation: ^2.1.0

  flutter_riverpod: ^2.3.5
  hooks_riverpod: ^2.3.5
  flutter_hooks: ^0.18.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # for data | state
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  freezed: ^2.3.2
  riverpod_generator: ^2.2.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/

  fonts:
    # - family: Mark
    #   fonts:
    #     - asset: fonts/Mark-Pro.ttf
    - family: SfPro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

# Generated by Spider
# For more info on configuration, visit https://birjuvachhani.github.io/spider/grouping/  
# Generates unit tests to verify that the assets exists in assets directory
spider:
  # Generates unit tests to verify that the assets exists in assets directory
  generate_tests: false
  # Use this to remove vcs noise created by the `generated` comments in dart code
  no_comments: true
  # Exports all the generated file as the one library
  export: true
  # This allows you to import all the generated references with 1 single import!
  use_part_of: true
  # Generates a variable that contains a list of all asset values.
  use_references_list: false

# Location where all the generated references will be stored
package: resources

groups:
  - path: assets/icons
    class_name: SvgIcons
    types: [ .svg ]
